# NUMPY

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.


In [5]:
import numpy as np;
a=np.array([1,2,3,4,5]);
b=np.array((6,7,8));

#can declare type of array as:-
c=np.array([12,45,61],dtype='f');

print(a);
print(type(a));

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(a.dtype); #dtype defines datatype in an array;

int32


In [7]:
print(c.dtype);

float32


In [9]:
d=np.array([[1,2],[3,4]]); #ndim defines whether given array is 1D, 2D and so on...
# or in other words, number of indices required to locate a given element.
# when we define multidimensional arrays, array elements in each item must be same.
print(a.ndim);
print(d.ndim);

1
2


In [11]:
print(d[0,1]);

2


In [13]:
e=np.array([[1,2],[3,4],[5,6],[7,8]])
print(e.ndim);

2


In [14]:
print(e[2,1]);

6


In [15]:
print(e.shape);
# we know e is 2D array, thus printing, number of 1D arrays then number of elements in each 1D array
# if 3D array, then (x,y,z) x:2d arrays, y:1d arrays, z:number of elements in each array.

(4, 2)


In [20]:
print(e.shape[0]);
# number of 1 d arrays
print(e.shape[1]);
# number of elements in each array

#if 3D array, 0,1,2 all valid, 0:2d arrays, 1:1d arrays, 2: elements in each

4
2


In [21]:
A=np.array(1);
print(A.ndim);

# only one element

0


In [22]:
print(a.size);
# no. of elements in that arraY

5


In [23]:
a=np.arange(10);
# generate elemnts in this range
print(a);

[0 1 2 3 4 5 6 7 8 9]


In [24]:
%whos


Variable   Type       Data/Info
-------------------------------
A          ndarray    : 1 elems, type `int32`, 4 bytes
a          ndarray    10: 10 elems, type `int32`, 40 bytes
b          ndarray    3: 3 elems, type `int32`, 12 bytes
c          ndarray    3: 3 elems, type `float32`, 12 bytes
d          ndarray    2x2: 4 elems, type `int32`, 16 bytes
e          ndarray    4x2: 8 elems, type `int32`, 32 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [25]:
a=np.arange(5,10);
print(a);

[5 6 7 8 9]


In [26]:
a=np.arange(5,20,2);
print(a);

[ 5  7  9 11 13 15 17 19]


In [29]:
a=np.random.permutation(np.arange(10));
# shuffle elements
print(a);

[7 9 8 4 2 5 0 3 1 6]


In [35]:
a= np.random.randint(100);
print(a);

59


In [34]:
a=np.random.rand(10);
print(a);

[0.52641154 0.73541144 0.34137729 0.25388769 0.57031828 0.30852803
 0.71330962 0.7871766  0.49219283 0.22242731]


In [40]:
d=np.arange(100).reshape(4,25);
print(d);

# give matrix with 100 elements, and size 2 x 25

[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24]
  [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
   48 49]]

 [[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
   73 74]
  [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
   98 99]]]


In [41]:
d=np.arange(100).reshape(2,2,25);
print(d);

[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24]
  [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
   48 49]]

 [[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
   73 74]
  [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
   98 99]]]


In [43]:
np.reshape?
# get info on that function
# np. (press tab) shows lists of functions

In [44]:
a=np.arange(100);
b=a[3:10];

print(b);


[3 4 5 6 7 8 9]


In [45]:
b[0]=-1;
print(b);

[-1  4  5  6  7  8  9]


In [46]:
print(a);

[ 0  1  2 -1  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


This shows b is also sharing same memory as that of a, so if we make changes in b, also change in a. To avoid it use copy function.

In [47]:
a=np.arange(100);
b=a[3:10].copy();

b[1]=-1;
print(a);

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [48]:
print(a[::])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [50]:
print(a[::-1])

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]


In [51]:
print(a[::5])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [52]:
a=np.arange(100).reshape(10,10);
print(a);

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [53]:
print(a.T);
# transpose

[[ 0 10 20 30 40 50 60 70 80 90]
 [ 1 11 21 31 41 51 61 71 81 91]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 3 13 23 33 43 53 63 73 83 93]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 7 17 27 37 47 57 67 77 87 97]
 [ 8 18 28 38 48 58 68 78 88 98]
 [ 9 19 29 39 49 59 69 79 89 99]]


In [60]:
a=np.arange(100);
a=a+5;
# add 5 to all elements (Broadcasting) (Adding a static value to a numpy array)
print(a);

[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104]


In [61]:
a=np.arange(10);
b=np.arange(10,20);

print(a);
print(b);

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [62]:
c=np.hstack((a,b))
print(c);

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [63]:
c=np.vstack((a,b));
print(c);

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [64]:
a=a[::-1];
print(a);


[9 8 7 6 5 4 3 2 1 0]


In [65]:
a.sort();
print(a);

[0 1 2 3 4 5 6 7 8 9]


In [73]:
a=np.arange(100);
%timeit sum(a);
%timeit np.sum(a);

# shows how fast numpy is

7.16 µs ± 171 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.29 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
